#! /usr/bin/env python
# 
# py2c takes as parameters a list of python files and creates one big C file
# that contains strings that are fed to the python interpreter.

import sys

try:
    ofile = open("py2cout.c", "w+")
except IOError:
    print "Unable to open py2cout.c"
    sys.exit(-1)

skel = 
"/* This code has been generated by py2c.py
#include <Python.h>"

ofile.write(skel)

for i in sys.argv[1:]:
    try:
        f = open(i, "r")
    except IOError:
        print "Unable to open " + i
        sys.exit(-1)

    c = f.read()
    

